name: Yunjian
options:
  bundleIdPrefix: com.yunjian
  deploymentTarget:
    iOS: "17.0"
    macOS: "14.0"

targets:
  YunjianApp:
    type: application
    platform: iOS
    settings:
      GENERATE_INFOPLIST_FILE: YES
      MARKETING_VERSION: 0.1.1
      CURRENT_PROJECT_VERSION: 2
    sources:
      - path: Apps/YunjianApp
    dependencies:
      - package: Yunjian
        product: UIComponents
      - package: Yunjian
        product: StorageService
      - package: Yunjian
        product: SyncEngine
      - package: Yunjian
        product: EditorEngine
      - package: Yunjian
        product: YunjianCore

  YunjianApp-macOS:
    type: application
    platform: macOS
    settings:
      GENERATE_INFOPLIST_FILE: NO
      INFOPLIST_FILE: Apps/YunjianApp/Info-macOS.plist
      PRODUCT_NAME: 云简
      MARKETING_VERSION: 0.1.1
      CURRENT_PROJECT_VERSION: 2
    sources:
      - path: Apps/YunjianApp
    dependencies:
      - package: Yunjian
        product: UIComponents
      - package: Yunjian
        product: StorageService
      - package: Yunjian
        product: SyncEngine
      - package: Yunjian
        product: EditorEngine
      - package: Yunjian
        product: YunjianCore

packages:
  Yunjian:
    path: .
